title: "antoine.studio"
description: "Documentation tool"
introduction: "This website ☼ is my digital studio, a place where I can experiment without ⁂ constraints. It's also my personal assistant, it helps me when I'm not sure how to do ✿ something I've done before. It invites me to write (and then find) my personal knowledge ⧉ online. Welcome&nbsp;✺"
main_url: "https://antoine.studio"
author_name: "Antoine Jaunard"
webring: False